spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/courseji?useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: ENC(LsjOGvs/THMPdc5JHoN11jkyLMLFk30RoJZpm9REA/T2LpcYjqE7dHd0nyD1V+rY)

jasypt:
  encryptor:
    password: littlecorgi

server:
  port: 10800