spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/courseji?useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: ENC(LsjOGvs/THMPdc5JHoN11jkyLMLFk30RoJZpm9REA/T2LpcYjqE7dHd0nyD1V+rY)

jasypt:
  encryptor:
    password: littlecorgi

server:
  port: 10800

logging:
  file:
    name: log

management:
  endpoints:
    web:
      exposure:
        include: "*"

qiniu:
  accessKey: ENC(I1HIg7i22MyTKUFJiILBE25XwMWTF70y9JWYEFuvVfl92zSquZkPZDkxc2E0cqNsngBahl8/ZgJ8LxEtS5wvEae3yxTfui45orYJaoYhLdU=)
  secretKey: ENC(OJcJ102vSe7Fr2ic34Tz38jaBHeUgsaCxm4T1NdfJhqWHKnpaAgnGaOypr/QlfzMB67Ms+NoV7RqMNQaQOp1CldcZTA0nOTwRyhJ8SgrWrI=)
  bucket: ENC(AukX9J7TsDGcySt+mxUmQV1k+ijby4O3CCTjZ1/wZwM7LK3QxvyvBB8BycYfEcWG)