spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/courseji?useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: ENC(SG7OHlPc4jAfHAr6VbQcgYCf7/BJ2l4hBNdVToqRsizLW+VPggCnZMqdX4nFnM+U)

jasypt:
  encryptor:
    password: littlecorgi