spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/courseji?useSSL=true
    username: courseji
    password: ENC(Tr1cNnImYGvCOr/WPxpFFC8UxwrR/1H6xgdIWw7QPJzfQ5hbPtd4+JZtoZOZ1uQt)

jasypt:
  encryptor:
    password: littlecorgi
