# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: show env message
        run: echo "::debug::dataBasePassword is ${{ secrets.ROOTPASSWORD }}"
      - name: Setup MySQL
        # You may pin to the exact commit or the version.
        # uses: mirromutth/mysql-action@de1fba8b3f90ce8db80f663a7043be3cf3231248
        uses: mirromutth/mysql-action@v1.1
        with:
          # MYSQL_ROOT_PASSWORD - root superuser password
          mysql root password: ${{ secrets.ROOTPASSWORD }} # optional, default is
          # MYSQL_DATABASE - name for the default database that is created
          mysql database: courseji # optional, default is
      - name: Build with Maven
        run: mvn -B package --file courseji/pom.xml
      - name: SCP Files
        # You may pin to the exact commit or the version.
        # uses: appleboy/scp-action@b476d5806f2a4c1ed5902a87fa91b0623cac7258
        uses: appleboy/scp-action@v0.0.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.PSERVER_ASSWORD }}
          source: "./courseji/target/courseji-0.0.1-SNAPSHOT.jar"
          target: "/root/CoursejiServer/"
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.PSERVER_ASSWORD }}
          script: |
            whoami
            nohup java -jar /root/CoursejiServer/courseji-0.0.1-SNAPSHOT.jar > courseji.txt &
